name: Cronjob

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '55,15 * * * *'

jobs:

  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update grondwaterpeil data
        run: make update_grondwaterpeildata
      - run: git config --name ${{ secrets.USERNAME }}
      - run: git config --email ${{ secrets.EMAIL }}
      - run: git add resource/archive/grondwaterpeildata.csv
      - run: git commit -m "Updated grondwaterpeildata"
      - run: git push