name: Graph

on: push

jobs:
  graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Make all targets
        env:
          ET_USERNAME: ${{ secrets.ET_USERNAME }}
          ET_PASSWORD: ${{ secrets.ET_PASSWORD }}
        run: make graph
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/website
      