name: Update grondwaterpeildata

on:
  schedule:
    # Run at 14:12 CET DST every day
    - cron:  '10 11 * * *'

jobs:
  update_grondwaterpeildata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get tags
        run: git fetch --tags origin
      - name: Install dependencies
        run: make install_dependencies
      - name: Update grondwaterpeil data
        env:
            ET_USERNAME: ${{ secrets.ET_USERNAME }}
            ET_PASSWORD: ${{ secrets.ET_PASSWORD }}
        run: make update_grondwaterpeildata TODAY=$(date +%Y%m%d)
      - run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global push.followTags true
          git add resource/archive/grondwaterdata/grondwaterpeildata.csv
          git commit -m "Updated grondwaterpeildata" || echo "No changes to commit"
          bin/create-tag.sh -p
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}