name: Update grondwaterpeildata

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '05 * * * *'

jobs:
  update_grondwaterpeildata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update grondwaterpeil data
        env:
            ET_USERNAME: ${{ secrets.ET_USERNAME }}
            ET_PASSWORD: ${{ secrets.ET_PASSWORD }}
        run: make update_grondwaterpeildata TODAY=$(date +%Y%m%d)
      - run: git config --global user.name ${{ secrets.USERNAME }}
      - run: git config --global user.email ${{ secrets.EMAIL }}
      - run: git add resource/archive/grondwaterdata/grondwaterpeildata.csv
      - run: git commit -m "Updated grondwaterpeildata"
      - run: git tag -a $(date +%Y%m%d) -m $(date +%Y%m%d)
      - run: git push
      - run: git push origin tag $(date +%Y%m%d)
