name: Update grondwaterpeildata

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '33 * * * *'

jobs:
  update_grondwaterpeildata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Update grondwaterpeil data
        env:
            ET_USERNAME: ${{ secrets.ET_USERNAME }}
            ET_PASSWORD: ${{ secrets.ET_PASSWORD }}
        run: make update_grondwaterpeildata TODAY=$(date +%Y%m%d)
      - run: |
          export TODAY=$(date +%Y%m%d)
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add resource/archive/grondwaterdata/grondwaterpeildata.csv
          git commit -m "Updated grondwaterpeildata" || echo "No changes to commit"
          git tag -a $TODAY -m $TODAY
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}